sudo: false
language: python
python:
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install coveralls
script:
- pycodestyle uw_coda
- python -m compileall uw_coda/
- coverage run uw_coda/test.py -v
after_script:
- coveralls
before_deploy:
- find uw_coda/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_coda/VERSION
deploy:
  provider: pypi
  user: uw-it-aca
  skip_cleanup: true
  password:
    secure: YXG3R/LIWdFG0IU7Ol93cPUCq97gxPV3i6QjcScZcQ2aWoAkFAgSDoBSKCtQusyQ16z2Ae7jhO6xoLQ5X7a9pnfE8mfAWyomTN1a5iEDmJzTljgzsqKNFvDIPYcALyPEZjJvwYxIm2IwYR4+v7OlsfiytlMcjl67JBs9AQqvONn9iByLJSMOHw8ZkE3vNWTxmumiBigQsHcmZybMO6AQFIt9Mwpkt/4/BMgF2DZA5dmrW/b+nmCqZ6DS9odfvRPzYiCgZHnkVMU7de/OPxuu8oeYlgciw28X7fHt6xvl91fVAf/9Qy1qHMh2akDMU0CUZj2t9a/jLy2Ssf8ohCrFu2aH7IssOII8EKSDH+YFw3lwA7v0ShDVP7ym2BPVrWlL9MOaKl8KTzSdexyV0cKtAT5tjBguyG6rs1NmEGon8VAIAUaKvIKCMvP3yawVbuFNU0xZek/XCctXcY+H0PX3VJieqbs/n/3qMOwhJLIwFkmzZmEg2W6Vf9H0fWwBFGqVL/7t0fZPkAdAul1tjsAfwcCcpnIQYs9IolEIhA7gX9cAEaEVdGHxH//KJ2cEJrAcgfW9QbsQKukQP0uuPx4/vHHteu29SMqp3Pu9iuBn2k4WutLO1zmHOzlJXEdLA7VNSLZkbE4+rpIUXzjcrvnWaOe+z8Toa65UjMhTYCmaquE=
  on:
    tags: true
    python: '3.6'
