sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
before_script:
- pip install -e .
- pip install pycodestyle
- pip install nose2
- pip install coverage
- pip install python-coveralls
script:
- pycodestyle uw_coda
- python -m compileall uw_coda/
- coverage run uw_coda/test.py -v
after_script:
- coveralls
before_deploy:
- find restclients_core/ -name \*.pyc -exec rm {} \;
- echo $TRAVIS_TAG > uw_coda/VERSION
